{% set name = "pgraph-python" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgraph-python-{{ version }}.tar.gz
  sha256: 4abad7ded90677e4d1fc8317de298c7068942f8b289ec9a58bf3d36d666e70cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - pgraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/pgraph-python
  summary: Simple graph functionality for Python.
  dev_url: https://github.com/petercorke/pgraph-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
