{% set name = "pgraph-python" %}
{% set version = "0.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ff41f718daf7ae925d36cd7d17f567b67479f115f073f497f985733ecbbc90b4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - spatialmath-python
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - pgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/petercorke/pgraph-python
  summary: Simple graph functionality for Python.
  dev_url: https://github.com/petercorke/pgraph-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
